# user-management-api/test/user.http
@host = http://localhost:8086/api/v1
@apiKey = william-hehe

###
GET {{host}}/users/e35c8ea9-6e46-47e3-bd0b-2496364e9ebe
Content-Type: application/json
X-API-Key: {{apiKey}}


###
POST {{host}}/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "name": "Khai",
  "email": "khai9@example.com",
  "password": "12345678"
}

