# user-management-api/test/user.http
@host = http://localhost:8086/api/v1
@apiKey = william-hehe

###
GET {{host}}/users/1772594263538205928
Content-Type: application/json
X-API-Key: {{apiKey}}


###
POST {{host}}/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "name": "Tai",
  "email": "tai@example.com",
  "age": 22,
  "password": "12345678",
  "level": 2
}