# user-management-api/test/user.http
@host = http://localhost:8086/api/v1
@apiKey = william-hehe
@uuid = 249370d3-1c7b-4332-adc0-62756e278f04
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiOTg1Tmc4SDVaNVAySHRtcmtQSWZ6ZGlGem1abThZWE52VmJ0d29uOG45ZmRYR25FR2JxVUpDWitZTWtrTFAwZGxEK3JjTUR0NnhoRDVGZEFiNjJlbGhSSDBLaXdMWUNNV1NJMmlVY1BWQ013Qi9scFVad1piR0dKVkpmd1VKQnVOdUZkU1hnTXV2OFNjR0RlRkNibWp4eEFHYm44SExPbUFGOG9rcHVZeE40PSIsImlzcyI6InVzZXItbWFuYWdlbWVudC1hcGkiLCJzdWIiOiIzMDQ3M2I0NS0xOTUzLTRkYmYtYTI3Yy02ZDBlMzZkNzY1NmIiLCJleHAiOjE3NzUwMDI4NDIsImlhdCI6MTc3NTAwMTk0MiwianRpIjoiMTY1NDExZmItNGEwOC00ZjJjLWE3NDMtMTJhNzVmNjNmMjg2In0.NDjNj4haz51Yw6M4lwYQEUM_IYtn4Qw-wwaICeDq65A
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzA0NzNiNDUtMTk1My00ZGJmLWEyN2MtNmQwZTM2ZDc2NTZiIiwiaXNzIjoidXNlci1tYW5hZ2VtZW50LWFwaSIsInN1YiI6IjMwNDczYjQ1LTE5NTMtNGRiZi1hMjdjLTZkMGUzNmQ3NjU2YiIsImV4cCI6MTc3NTYwNjc0MiwiaWF0IjoxNzc1MDAxOTQyLCJqdGkiOiJjMTVlZGU5My02MWRhLTQyZDgtYjU1MC02NzI1YWQ3MjNiYTQifQ.RBveXnV_BgiM4koBDFmewnVT46h0lkyZChRbYAhl3o0

###
POST {{host}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzA0NzNiNDUtMTk1My00ZGJmLWEyN2MtNmQwZTM2ZDc2NTZiIiwiaXNzIjoidXNlci1tYW5hZ2VtZW50LWFwaSIsInN1YiI6IjMwNDczYjQ1LTE5NTMtNGRiZi1hMjdjLTZkMGUzNmQ3NjU2YiIsImV4cCI6MTc3NTYwNjc0MiwiaWF0IjoxNzc1MDAxOTQyLCJqdGkiOiJjMTVlZGU5My02MWRhLTQyZDgtYjU1MC02NzI1YWQ3MjNiYTQifQ.RBveXnV_BgiM4koBDFmewnVT46h0lkyZChRbYAhl3o0"
}


###
POST {{host}}/auth/refresh-token
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzA0NzNiNDUtMTk1My00ZGJmLWEyN2MtNmQwZTM2ZDc2NTZiIiwiaXNzIjoidXNlci1tYW5hZ2VtZW50LWFwaSIsInN1YiI6IjMwNDczYjQ1LTE5NTMtNGRiZi1hMjdjLTZkMGUzNmQ3NjU2YiIsImV4cCI6MTc3NTYwNjc0MiwiaWF0IjoxNzc1MDAxOTQyLCJqdGkiOiJjMTVlZGU5My02MWRhLTQyZDgtYjU1MC02NzI1YWQ3MjNiYTQifQ.RBveXnV_BgiM4koBDFmewnVT46h0lkyZChRbYAhl3o0"
}


### Login
POST {{host}}/auth/login
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "email": "nguyenvana7@example.com",
  "password": "123456"
}


###
GET {{host}}/users?limit=10&offset=0&search=Nguyen&sort=created_at&order=desc
X-API-Key: {{apiKey}}
Authorization: Bearer {{access_token}}


###
DELETE {{host}}/users/{{uuid}}
X-API-Key: {{apiKey}}

###
PATCH {{host}}/users/{{uuid}}/restore
X-API-Key: {{apiKey}}


###
PUT {{host}}/users/249370d3-1c7b-4332-adc0-62756e278f04
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "fullname": "Nguyen Van B",
  "age": 30
}

###
POST {{host}}/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "fullname": "Nguyen Van A 8",
  "email": "nguyenvana8@example.com",
  "password": "123456",
  "age": 25
}


###
GET {{host}}/users/249370d3-1c7b-4332-adc0-62756e278f04
X-API-Key: {{apiKey}}


###
GET {{host}}/users/e35c8ea9-6e46-47e3-bd0b-2496364e9ebe
Content-Type: application/json
X-API-Key: {{apiKey}}


###

