# user-management-api/docker-compose.yml
# docker network ls
# docker compose up -d
# docker compose pull pgadmin
# docker compose up -d pgadmin

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - app
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: go-app
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend-network:
    external: true