// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserFullname string    `json:"user_fullname"`
	UserEmail    string    `json:"user_email"`
	UserPassword string    `json:"user_password"`
	// Age of user (1-150)
	UserAge *int32 `json:"user_age"`
	// 1: active, 2: inactive, 3: banned
	UserStatus int32 `json:"user_status"`
	// 1: admin, 2: moderator, 3: member
	UserLevel     int32      `json:"user_level"`
	UserDeletedAt *time.Time `json:"user_deleted_at"`
	UserCreatedAt time.Time  `json:"user_created_at"`
	UserUpdatedAt time.Time  `json:"user_updated_at"`
}
