// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Profile struct {
	ProfileID   int64  `json:"profile_id"`
	UserID      int64  `json:"user_id"`
	PhoneNumber string `json:"phone_number"`
	Address     string `json:"address"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	Uuid           uuid.UUID `json:"uuid"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
	PhoneNumber    string    `json:"phone_number"`
	HashedPassword string    `json:"hashed_password"`
}
