// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    hashed_password
) VALUES (
    $1, $2, $3
)
RETURNING user_id, uuid, name, email, created_at, phone_number, hashed_password
`

type CreateUserParams struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.HashedPassword,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, uuid, name, email
FROM users
WHERE user_id = $1
LIMIT 1
`

type GetUserRow struct {
	UserID int64     `json:"user_id"`
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Email  string    `json:"email"`
}

func (q *Queries) GetUser(ctx context.Context, userID int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i GetUserRow
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Email,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT user_id, uuid, name, email, created_at, phone_number, hashed_password
FROM users
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.HashedPassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, uuid, name, email, created_at, phone_number, hashed_password
FROM users
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.PhoneNumber,
			&i.HashedPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    email = $3
WHERE user_id = $1
RETURNING user_id, uuid, name, email, created_at, phone_number, hashed_password
`

type UpdateUserParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.UserID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.HashedPassword,
	)
	return i, err
}
