// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users
WHERE (
    $1::bool IS NULL
    OR ($1::bool = TRUE AND user_deleted_at IS NOT NULL)
    OR ($1::bool = FALSE AND user_deleted_at IS NULL)
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR user_email ILIKE '%' || $2::text || '%'
    OR user_fullname ILIKE '%' || $2::text || '%'
)
`

type CountUsersParams struct {
	Deleted *bool   `json:"deleted"`
	Search  *string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Deleted, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_fullname,
    user_email,
    user_password,
    user_age,
    user_status,
    user_level
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
`

type CreateUserParams struct {
	UserFullname string `json:"user_fullname"`
	UserEmail    string `json:"user_email"`
	UserPassword string `json:"user_password"`
	UserAge      *int32 `json:"user_age"`
	UserStatus   int32  `json:"user_status"`
	UserLevel    int32  `json:"user_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserFullname,
		arg.UserEmail,
		arg.UserPassword,
		arg.UserAge,
		arg.UserStatus,
		arg.UserLevel,
	)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const deleteUserHard = `-- name: DeleteUserHard :exec
DELETE FROM users
WHERE user_uuid = $1
`

func (q *Queries) DeleteUserHard(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserHard, userUuid)
	return err
}

const deleteUserSoft = `-- name: DeleteUserSoft :one
UPDATE users
SET user_deleted_at = NOW()
WHERE user_uuid = $1
AND user_deleted_at IS NULL
RETURNING user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
`

func (q *Queries) DeleteUserSoft(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUserSoft, userUuid)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
FROM users
WHERE user_email = $1
AND user_deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
FROM users
WHERE user_uuid = $1
AND user_deleted_at IS NULL
`

func (q *Queries) GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, userUuid)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
FROM users
WHERE user_deleted_at IS NULL
ORDER BY user_created_at DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserUuid,
			&i.UserFullname,
			&i.UserEmail,
			&i.UserPassword,
			&i.UserAge,
			&i.UserStatus,
			&i.UserLevel,
			&i.UserDeletedAt,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersOrderByCreatedAtDesc = `-- name: ListUsersOrderByCreatedAtDesc :many
SELECT user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
FROM users
WHERE user_deleted_at IS NULL
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR user_email ILIKE '%' || $3::text || '%'
    OR user_fullname ILIKE '%' || $3::text || '%'
)
ORDER BY user_created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersOrderByCreatedAtDescParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

func (q *Queries) ListUsersOrderByCreatedAtDesc(ctx context.Context, arg ListUsersOrderByCreatedAtDescParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersOrderByCreatedAtDesc, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserUuid,
			&i.UserFullname,
			&i.UserEmail,
			&i.UserPassword,
			&i.UserAge,
			&i.UserStatus,
			&i.UserLevel,
			&i.UserDeletedAt,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET user_deleted_at = NULL
WHERE user_uuid = $1
AND user_deleted_at IS NOT NULL
RETURNING user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
`

func (q *Queries) RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, userUuid)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    user_password = COALESCE($1, user_password),
    user_fullname = COALESCE($2, user_fullname),
    user_age = COALESCE($3, user_age),
    user_status = COALESCE($4, user_status),
    user_level = COALESCE($5, user_level)
WHERE user_uuid = $6
AND user_deleted_at IS NULL
RETURNING user_uuid, user_fullname, user_email, user_password, user_age, user_status, user_level, user_deleted_at, user_created_at, user_updated_at
`

type UpdateUserParams struct {
	UserPassword *string   `json:"user_password"`
	UserFullname *string   `json:"user_fullname"`
	UserAge      *int32    `json:"user_age"`
	UserStatus   *int32    `json:"user_status"`
	UserLevel    *int32    `json:"user_level"`
	UserUuid     uuid.UUID `json:"user_uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserPassword,
		arg.UserFullname,
		arg.UserAge,
		arg.UserStatus,
		arg.UserLevel,
		arg.UserUuid,
	)
	var i User
	err := row.Scan(
		&i.UserUuid,
		&i.UserFullname,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserAge,
		&i.UserStatus,
		&i.UserLevel,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET user_password = $2
WHERE user_uuid = $1
`

type UpdateUserPasswordParams struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserPassword string    `json:"user_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserUuid, arg.UserPassword)
	return err
}
